/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class nl_kb_jp2_JP2Reader */

#ifndef _Included_nl_kb_jp2_JP2Reader
#define _Included_nl_kb_jp2_JP2Reader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     nl_kb_jp2_JP2Reader
 * Method:    getJp2Specs
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_nl_kb_jp2_JP2Reader_getJp2Specs
  (JNIEnv *, jclass, jstring);

/*
 * Class:     nl_kb_jp2_JP2Reader
 * Method:    getJp2Specs
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL JNICALL Java_nl_kb_jp2_JP2Reader_getTile
  (JNIEnv *, jclass, jstring, jint, jint, jobjectArray);


#ifdef __cplusplus
}
#endif
#endif
